#!/usr/bin/env node
// Regenerates assets/data.js (window.CE_DATASET) from assets/data.json.
// Run this after every edit to assets/data.json and commit both files together.

const fs = require('fs');
const path = require('path');

const srcPath = path.join(__dirname, '..', 'assets', 'data.json');
const outPath = path.join(__dirname, '..', 'assets', 'data.js');

const data = JSON.parse(fs.readFileSync(srcPath, 'utf8'));

const banner =
  '// Generated by tools/build-data.js from assets/data.json — do not hand-edit.\n' +
  '// Run `node tools/build-data.js` after changing assets/data.json and commit both files.\n';

fs.writeFileSync(outPath, `${banner}window.CE_DATASET = ${JSON.stringify(data, null, 2)};\n`);

console.log(`Wrote ${outPath} (${data.sections.length} sections, ${data.questions.length} questions).`);
